LIST_DASHBOARD_NAMES = ('Twitter', 'WallStreetBets', 'Chart', 'Stocktwits', 'Pattern')

TWITTER_TRADER_USERNAMES = [
    "",
    'traderstewie',
    'the_chart_life',
    'canuck2usa',
    'sunrisetrader',
    'tmltrader'
]


TWITTER_CRYPTOUSER_USERNAMES = [
    "",
    'crypto_bird',
    'CryptoHornHairs',
    'Broccolex',
    'CryptoInsiderX',
    'binance',
    'ZclassicCoin',
    'BitMEX',
    'Haejin_Crypto',
    'LedgerFund',
    'OpenZeppelin',
    'ProfessorCrypto',
    'ActualAdviceBTC',
    'ForbesCrypto',
    'thetermsheet',
    'twobitidiot',
    'CryptoCobain',
    'Eug_Ng',
    'krugermacro',
    'coin_signals',
    'qturn',
    'GolfViews18',
    'koreanjewcrypto',
    'BitcoinBirch',
    'dragonchaingang',
    'Beetcoin',
    'SecretsOfCrypto',
    'Crypto_Ed_NL',
    'CryptoMessiah',
    'bapao83',
    'krokotar',
    'Mansa_Godson',
    'iamjosephyoung',
    'kyletorpey',
    'KyleSamani',
    'multicoincap',
    'coinfund_io',
    'fundstrat',
    'BlockFi',
    'Algo4Crypto',
    'glynmaclean',
    'Makilisg',
    'maxdesalle',
    'Uniswap',
    'JeffriesDavid23',
    'FundamentalWolf',
    'LegendOfCrypto',
    'CryptoYoda1338',
    'circlepay',
    'crypto_rand',
    'jerallaire',
    'OneMorePeter',
    'Ecoinamist',
    'PanteraCapital',
    'blockchaincap',
    'Blockstream',
    'TomoChainANN',
    'scalarcapital',
    'Blue_Protocol',
    'QcgRoyal',
    '21CRYPTOS',
    'DeFi_Lunar8',
    'woonamic',
    'TheCryptoFam',
    'atltrading_',
    'HeyTaiZen'
]

TWITTER_CATEGORY = ['Crypto', 'Stock']